### ISSUE TITLE
backend capabilities for interview-experience feature

### ISSUE THREAD

**Issue by Joyeleke** [colorstackorg/oyster#129]
### Description

An important feature request by ColorStack members is being able to share and view interview experiences for various companies - following the trend of features like compensation data and company features. This issue focuses on the backend features needed to make this possible and is linked to issue #120 .

### Technical Plan

On the backend, in the core package:

1. Implement a database migration that creates a interview_experiences SQL table.
2. Implement a uploadInterviewExperience function, which accepts some interview experience data and saves it to the interview_experiences table.
3. Implement a listInterviewExperience function, which accepts some query parameters to support pagination and returns a list of experiences.

**Comment by ramiAbdou** [comment]
Temporarily closing for now until we approve the initial discussion!

**Comment by ramiAbdou** [comment]
Temporarily closing for now until we approve the initial discussion!
