### ISSUE TITLE
Create `extensions.json` to recommend VSCode extensions 🗣️

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#163]
### Description

VSCode supports an [`extensions.json`](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) file to recommend extensions when the workspace is opened for the first time. This would make it even easier for new contributors to onboard.

Currently, we list out our recommend extensions in our [`README.md`](https://github.com/colorstackorg/oyster/blob/1fe26e432ab19fffef421403402ac7ceb49150f9/CONTRIBUTING.md?plain=1#L193).

### Acceptance Criteria

This issue will be complete when an `extensions.json` file is created in the `.vscode` folder and adds the recommended extensions that are currently in the [`README.md`](https://github.com/colorstackorg/oyster/blob/1fe26e432ab19fffef421403402ac7ceb49150f9/CONTRIBUTING.md?plain=1#L193).

**Comment by Baguirre03** [comment]
Hi I am willing to take this on! I attached the PR for this issue! 
https://github.com/colorstackorg/oyster/pull/179

**Comment by ramiAbdou** [comment]
Awesome, thanks @Baguirre03!
