### ISSUE TITLE
Add an upcoming Airmeet event in Admin Dashboard 📆

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#170]
### Description

Whenever the next Airmeet event is ready to put in the Member Profile, I have to manually create a Bull job in the Admin Dashboard  to sync an Airmeet event. It's a little tedious to do this, so would like to improve the UX around this.

### Acceptance Criteria

In the Admin Dashboard -> Events page, there is a menu button with the option to `Create Event`.

There should be an additional button that says `Sync Airmeet Event` which opens up a modal allowing the user to submit an Airmeet ID. Upon clicking submit, the Airmeet event should be created in our database (and thus populated in the Member Profile).

### Additional Context

We already have a Bull job called [`event.sync`](https://github.com/colorstackorg/oyster/blob/ab7018cb2da0837bcf7996dd6d88be627b105ff3/packages/core/src/modules/event/event.worker.ts#L28) that handles the backend logic for syncing the event, we'll just need to emit this job (ie: call the [`job`](https://github.com/colorstackorg/oyster/blob/ab7018cb2da0837bcf7996dd6d88be627b105ff3/packages/core/src/infrastructure/bull/use-cases/job.ts#L7) function) when submitting that form described above.

**Comment by Joyeleke** [comment]
I would work on this!
