### ISSUE TITLE
Slow loading time for the home page due to leaderboard query ⏰

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#171]
### Description

We have a cool "Active Streak Leaderboard" on the home page, but it is quite slow and significantly hurts the user experience when it takes a long time to load. Part of the issue is that the query to retrieve the logged-in user's leaderboard position is unique to the individual, so caching only so much. For the majority of users who don't use the Member Profile religiously, they will have a bad first page load.

### Acceptance Criteria

Still TBD - needs investigation. If we can speed up the query, we'll opt for that. If we can't, we may consider using Remix's [`defer`](https://remix.run/docs/en/main/utils/defer) functionality and just use spinners. We can also remove/move the leaderboard altogether (this seems unlikely).

### Additional Context

Here are the related functions to investigate:
- [`getActiveStreakLeaderboard`](https://github.com/colorstackorg/oyster/blob/ab7018cb2da0837bcf7996dd6d88be627b105ff3/packages/core/src/modules/active-status/queries/get-active-streak-leaderboard.ts#L7)
- [`getActiveStreakLeaderboardPosition`](https://github.com/colorstackorg/oyster/blob/ab7018cb2da0837bcf7996dd6d88be627b105ff3/packages/core/src/modules/active-status/queries/get-active-streak-leaderboard-position.ts#L7)

Here is the leaderboard in reference:

![Screenshot 2024-04-26 at 2 40 51 PM](https://github.com/colorstackorg/oyster/assets/38056800/4ac7508b-6015-452c-82c8-f1139b576f0a)

**Comment by ayoaru** [comment]
Was thinking about this issue, do we necessarily need to retrieve the user's position on the leaderboard if it isn't, say, top 20?
> Though only top 10 is displayed, maybe it should just be top 10?

From what I've noticed, the active streak leaderboard rarely changes and someone's position depends more on what someone else does/does not do, versus the points leaderboard, which is much more easily impacted by what a user themself does.

**Comment by ramiAbdou** [comment]
That's a great point, @ayoaru! I'm actually okay with the tradeoff of not showing the user's position on the leaderboard given that it's an expensive query. We wouldn't be able to show it for only the top 20 because we'd still have to run the query to determine whether they are top 20 or not. Thinking we could just scrap it altogether.

Would you be down to take this on?

**Comment by ayoaru** [comment]
I'd be down! If we keep it, another alternative is that since it shows top 10, we only check the status of those top 10 members (again due to the unlikeliness of change). If one or more fall out the top 10, then we get the new positions. I'm not sure how the data is stored in the tables, can it not be sorted by who has the longest streak?

**Comment by ramiAbdou** [comment]
Unfortunately the data isn't stored in a way that allows us to sort easily - we have to compute the "streaks" on the fly. We could do some work to store some additional data in like a "streaks" column, but I'm leaning against that mainly because I like the idea of scrapping the "individual" position on the leaderboard and just doing the top 10 query.

One benefit of doing the top 10 query is caching is it extremely efficient because we can just cache that query until the start of the next week (when the streaks gets updated), so it'll be a cache hit for literally everybody that hits the "Home" page (except the first person).

**Comment by ayoaru** [comment]
Alright, I'll remove the user position query and make a PR once I've verified it doesn't affect anything.

**Comment by ramiAbdou** [comment]
Hey @ayoaru - I've been working on some performance improvements in some other areas of the Member Profile, I'm going to wrap up this ticket as well if that's okay with you!

**Comment by ayoaru** [comment]
@ramiAbdou No worries, sorry it slipped off my radar! Will just work on #216

**Comment by ramiAbdou** [comment]
All good, that sounds great!
