### ISSUE TITLE
Ability to accept mistakenly rejected applications ✅

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#172]
### Description

Sometimes, we mistakenly reject some applications that should've been accepted. Right now, that person would have to send in another application in order to get accepted.

### Acceptance Criteria

Here are some acceptance criteria:
- As an admin, when I filter for rejected applications, I should see a menu button appear at the end of each application row.
- As an admin, when I click the "Accept Application" menu button, a confirmation modal should pop up.
- As an admin, when the confirmation modal pops up and I click confirm, the member should be accepted.

### Additional Context

We already have the [`acceptApplication`](https://github.com/colorstackorg/oyster/blob/ab7018cb2da0837bcf7996dd6d88be627b105ff3/packages/core/src/modules/application/use-cases/accept-application.ts#L7) function which handles the backend for this, so this is mainly a frontend task.

**Comment by tomas-salgado** [comment]
I'd like to take this one!

**Comment by tomas-salgado** [comment]
I noticed there's a Documentation tag. Is there any documentation that needs to be modified or created as part of this issue?
