### ISSUE TITLE
Goody (DoorDash) API Integration - Gift Cards 🎁

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#187]
### Description

We typically reward members who are in the Top 75 of the leaderboard of a Fam Friday session with an AlgoExpert license as well as a DoorDash gift card. To administer the DoorDash gift cards, we use a service called [Goody](https://www.ongoody.com).

We want to build an integration with the Goody API so that we can make sending these gifts as easy as a few clicks in our Admin Dashboard. Eventually, we can build a deeper integration with the Airmeet API and automatically grab the top 75 in the leaderboard, so sending gift cards would be a 1-click task! The latter part we'll save for the next iteration.

For now, we'll build a simple integration with the [Goody Automation API](https://developer.ongoody.com/automation-api/create-an-order), which allows us to send gifts to multiple people.

### Acceptance Criteria

This issue should do the following:
- Implement the ability to send Goody gifts, using their API (ie: [`POST /v1/order_batches`](https://developer.ongoody.com/automation-api/create-an-order)).
  - You can assume that the `product_id` is read from an environment variable (ie: `GOODY_DOORDASH_PRODUCT_ID`).
- In the Admin Dashboard -> Students page, add an option when clicking on the row's option to "Send Goody Gift". This should open a modal which contains a form asking for the "Gift", which for now should have "DoorDash Gift Card" as the only option.
- Upon submitting the form above, this should send the gift to the member. This should also send an internal Slack notification.

Don't worry about testing this - just implement 90% and I'll jump in to help testing with a real Goody API key.

**Comment by ramiAbdou** [comment]
@sajjad-source

**Comment by sajjad-source** [comment]
ty! would love to work on this

**Comment by tomas-salgado** [comment]
Hey @sajjad-source! Are you still working on this issue? No worries if not, just let me know so we can open it up for someone else!

**Comment by tomas-salgado** [comment]
Going to open up this issue!

**Comment by sajjad-source** [comment]
Hey @tomas-salgado. Really sorry I just saw your messages and had completely forgot about this issue 😅. Have had a lot on my plate since school ended, but I hope to be able to contribute again when space opens up. Thanks for opening up the issue again

**Comment by nicholasg2001** [comment]
If this issue is back up for grabs I'm down to work on it!

**Comment by tomas-salgado** [comment]
@nicholasg2001 You've got it!

**Comment by nicholasg2001** [comment]
@ramiAbdou Still learning the codebase so I just have a clarifying question. For the goody API code, should I be creating a folder `goody` inside of `packages/core/src/modules`?

**Comment by tomas-salgado** [comment]
@nicholasg2001 just realized we missed this question, apologies. For now it should be fine to just have the folder `goody` in that location. 

Let me know if you still plan on working on this issue!

**Comment by omar-elbaz** [comment]
I'd be down to take it @nicholasg2001 if you're no longer working on it. LMK

**Comment by nicholasg2001** [comment]
You can take it!

**Comment by omar-elbaz** [comment]
@tomas-salgado Im working on it! assign me

**Comment by omar-elbaz** [comment]
Got a little bit of help from @RiosNicholas can we add him as an assignee as well? (bro barely did anything ngl but lets show him some love)

**Comment by RiosNicholas** [comment]
LMAO, nah I cooked with the frontend @omar-elbaz

**Comment by RiosNicholas** [comment]
> Got a little bit of help from @RiosNicholas can we add him as an assignee as well? (bro barely did anything ngl but lets show him some love)

chill, I cooked with the frontend @omar-elbaz

**Comment by RiosNicholas** [comment]
I think you assigned the wrong Nicholas, lol @tomas-salgado

**Comment by tomas-salgado** [comment]
Ahh mb 😆
