### ISSUE TITLE
Points page takes a long time to load ⏰

### ISSUE THREAD

**Issue by Abdisalanx0** [colorstackorg/oyster#206]
### Description

When you click on the points tab it takes a long time to display the page!

### Steps to Reproduce

1. Go to Member Profile.
2. Click on points tab

### Expected Behavior

It probably should load faster

### why its happening?
- I believe its having trouble loading all of the users? 
- Earlier this week it was having no trouble, Maybe the latest pr slowed down the load time?
- Maybe we could implement a way to load the page first then the data and potentially have a skeleton of the data until it loads?

**Comment by Abdisalanx0** [comment]
@ramiAbdou Its not loading for 10s anymore. idk why 🤔

**Comment by ramiAbdou** [comment]
No worries, it might have been a fluke. I can confirm that it's not taking very long for me either. If the issue persists later, feel free to reopen this!

**Comment by ramiAbdou** [comment]
Reopening this as it's not quite 10 seconds slow, but it is a slow query and I found the culprit!

**Comment by Abdisalanx0** [comment]
Nice! I also realized that if someone gets too many points  too fast it slows it down. Seems like your change fixed it though
