### ISSUE TITLE
Application "Reviewed By" Field

### ISSUE THREAD

**Issue by jenniferc2011** [colorstackorg/oyster#215]
### Description

To ensure that ambassadors are reviewing applications and sharing the workload evenly, we should add a "Reviewed By" field which displays the name of the admin who reviewed an application. This should persist across all views (ie: accepted, rejected, pending, all).

### Acceptance Criteria

In the "Applications" table, we should a column called "Reviewed By" which is displayed after the "Status" column.

### Additional Context

There is already a `reviewed_by_id` column that lives in the `applications` table, so we'll just need to use that ID to grab the full name information from the `admins` table.

**Comment by Boris713** [comment]
Can I have this one?

**Comment by tomas-salgado** [comment]
@wflore19 there's a similar PR [here](https://github.com/colorstackorg/oyster/pull/237) in case you want to reference that as well

**Comment by wflore19** [comment]
@tomas-salgado Question: If I want to add a row to `applications` & `admins` for testing, do I add a transaction to the `seed()` function in [seed.ts](https://github.com/wflore19/oyster/blob/main/packages/db/src/scripts/seed.ts)? Or create a new migration for inserting?

**Comment by wflore19** [comment]
I think I figured it out. 

- Create new migration for insert
- Run 'yarn db:migrate'
- Delete new migration file (we don't want this in prod)

**Comment by tomas-salgado** [comment]
Yep, that approach should work! I'll also note that if you're trying to insert values directly into the database, it's also possible to do it from the terminal by running 
```
psql postgresql://oyster:oyster@localhost:5433/oyster
```
From here, you can interact directly with the database, and update values or tables with SQL commands as well

**Comment by wflore19** [comment]
@tomas-salgado Thanks I got it working and created documentation for newcomers on interacting with the development database. [#338](https://github.com/colorstackorg/oyster/pull/338)

**Comment by tomas-salgado** [comment]
Wow that looks great!! Thanks so much for writing that up!
