### ISSUE TITLE
Add context/messaging to frequent rejection reasons 💬

### ISSUE THREAD

**Issue by jenniferc2011** [colorstackorg/oyster#216]
### Description

We get a lot of emails from applicants on why they were rejected from the community. To fix this, we should add some more context to the rejection email. This should ideally result in the less emails being sent to our support.

Here are some frequent rejection reasons:
- Not an undergrad student.
- Incorrect or suspicious LinkedIn.
- Not the right major.
- Not enrolled in US or Canada.

### Acceptance Criteria

For this issue to be complete, you'll need to:
- Make the "Reject" button go to a new modal that displays a form that allows you to select a "Reason".
- Show the "Rejection Reason" in the "Applications" table in the Admin Dashboard. Note that this should only be in the "Rejected" and "All" views.
- Update the email template `application-rejected` email template to take in a dynamic `reason` and display it accordingly.

**Comment by ayoaru** [comment]
I think I could give this one a shot!

**Comment by ramiAbdou** [comment]
Awesome, it's yours @ayoaru! Sorry for the lack of clarity on the UI (I need to get us on Figma soon), so don't worry too much about that and I can jump in after you've implemented the core logic to help nail that down.

**Comment by ayoaru** [comment]
Taking a look at this sometime today or tomorrow! Been settling into my internship 😅

**Comment by tomas-salgado** [comment]
Going to open up this issue!

**Comment by arelymartinez16** [comment]
I would like to work on this :)

**Comment by jenniferc2011** [comment]
Yessss Arely!!! 💚💚💚

**Comment by arelymartinez16** [comment]
I completed the first task about a week ago, and I am finishing up the second task right now. Do I have to add rejection reason to the database as well? I am currently struggling with that.
