### ISSUE TITLE
Add "swag pack eligibility" page 📆

### ISSUE THREAD

**Issue by jenniferc2011** [colorstackorg/oyster#219]
### Description

On June 9th, 2023, we launched our new activation flow which is a process for new members to get activated and claim swag packs upon activation. Every so often, we'll have a member who joined before June 9th who wants a swag pack, but unfortunately they will not be able to go through activation and get one.

We should implement a "swag pack eligibility" page which makes it really clear if a member qualifies for a swag pack based on when they joined and if they've already received a swag pack or not.

### Acceptance Criteria

To implement this issue, implement a page which shows a modal (on top of the home page, ie: `/home/swag-pack/eligibility`) that shows a _different_ message for the following cases:
- If the member has already claimed a swag pack.
- If the member is activated, but hasn't claimed a swag pack.
- If the member joined before the activation date.

Note: Don't worry about the messages itself, @ramiAbdou will help come up with those after opening the PR if necessary.

**Comment by ramiAbdou** [comment]
@jenniferc2011 I definitely understand the problem we're solving, and I like the solution you mentioned. I'm going to evolve it slightly to be a "swag pack eligibility page" that is custom for each member, which lets them know if they qualify and if not, then why not.

I'll update the original description!

**Comment by ramiAbdou** [comment]
@Boris713 Just updated the requirements, but I'm assigning to you now!

**Comment by wflore19** [comment]
is this issue [solved](https://github.com/colorstackorg/oyster/blob/4999e069407eaaae97db52b821f9a7174e3eebd2/apps/member-profile/app/routes/_profile.home.tsx#L241)?

**Comment by ramiAbdou** [comment]
Nope, you can take it @wflore19!

**Comment by wflore19** [comment]
@ramiAbdou i'm going to release this

**Comment by tomas-salgado** [comment]
I've got this one 🫡
