### ISSUE TITLE
Add an "Admins" tab in the Admin Dashboard 👥

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#248]
### Description

See #247 for project overview.

### Acceptance Criteria

This issue should:
- Add an "Admins" tab in the Admin Dashboard sidebar.
- Add a new route at `/admins`. For now, this should just be a blank page.

### Additional Context

  - [Here](https://github.com/colorstackorg/oyster/blob/main/apps/admin-dashboard/app/routes/_dashboard.tsx#L61) is where those navigation items are specified.
  - To add a new route, you just need to create a new file in the `routes` folder (ie: `_profile.admins.tsx`). For more information on routing in Remix, see [here](https://remix.run/docs/en/main/discussion/routes). A blank route should look something like this:
    ```tsx
    import { json, type LoaderFunctionArgs } from '@remix-run/node';

    import { ensureUserAuthenticated } from '@/shared/session.server';

    export async function loader({ request }: LoaderFunctionArgs) {
      await ensureUserAuthenticated(request);

      return json({});
    }

    export default function AdminsPage() {
      return null;
    }
    ```

**Comment by BeteabTefera** [comment]
@ramiAbdou I will take this, good first issue

**Comment by ramiAbdou** [comment]
Perfect, you got it!

**Comment by BeteabTefera** [comment]
@ramiAbdou status update: Just got back from vacation, been hectic with internship starts tmr, expect this to be done no later than this week
