### ISSUE TITLE
View admins in the Admin Dashboard 👥

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#249]
### Description

See #247 for project overview.

### Acceptance Criteria

This issue should:
- Add a table to the `/admins` page which shows the following information about admins:
   - First Name
   - Last Name
   - Email
   - Access (Full / Ambassador)

There no need to worry about pagination for this since we won't ever have a ton of admins.

### Additional Context

  - You can add the backend query (ie: `listAdmins`) in the `core` package. There is already an [admin](https://github.com/colorstackorg/oyster/tree/main/packages/core/src/modules/admin) modules in the `core` package, you'll likely need to add a `queries` folder in that module.
  - You can find inspiration from our other pages in the Admin Dashboard that do something similar. See how we implemented the [feature flags page](https://github.com/colorstackorg/oyster/blob/main/apps/admin-dashboard/app/routes/_dashboard.feature-flags.tsx) as it'll be nearly identical.

**Comment by reaganrazon** [comment]
I can take this after @BeteabTefera 's ticket

**Comment by BeteabTefera** [comment]
> I can take this after @BeteabTefera 's ticket is implemented or we can coordinate

I would love to coo-rdinate!

**Comment by ramiAbdou** [comment]
Awesome, thanks y'all! Just assigned to you @reaganrazon!

**Comment by reaganrazon** [comment]
@ramiAbdou Do you want the admins table to be viewed with the dashboard on the left? In the preceding issue, it said you can create a new file in `routes` called : "_profile.admins.tsx" but using this route would render a table on a screen by itself.  

Attached are two images, one using _dashboard. and one using _profile. 
<img width="1181" alt="image" src="https://github.com/colorstackorg/oyster/assets/115665609/ce837cf8-0fa0-4f4d-94bf-1bd699b173ac">

<img width="1160" alt="image" src="https://github.com/colorstackorg/oyster/assets/115665609/3976372e-92f9-43d3-956f-6276aacc2709">

**Comment by reaganrazon** [comment]
Question is resolved!^
