### ISSUE TITLE
Remove admin access in the Admin Dashboard 👥

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#250]
### Description

See #247 for project overview. Note that this is dependent on #249 being implemented first.

### Acceptance Criteria

This issue should:
- Add a dropdown to the table in the `/admins` page, which has the option to remove access from the Admin Dashboard.
- Clicking the dropdown option should open a confirmation modal (ie: `/admins/remove`). In that modal, clicking a "Remove" button should officially remove access from the Admin Dashboard and they should no longer appear in the Admins table. Note that it shouldn't delete the record entirely, but it should set the `deletedAt` timestamp, effectively archiving the admin).

### Additional Context

  - You can add the backend functionality (ie: `removeAdmin`) in the `core` package. There is already an [admin](https://github.com/colorstackorg/oyster/tree/main/packages/core/src/modules/admin) module in the `core` package, you'll just need to add the function to the `use-cases` folder in that module.

**Comment by BeteabTefera** [comment]
@ramiAbdou Discussed with @reaganrazon and she will take the lead and i will pair program with her to see how she implement (learning from her)it please assign to her, thank you :)

**Comment by ramiAbdou** [comment]
@reaganrazon can you comment on this ticket so I can assign you to it as well?

**Comment by reaganrazon** [comment]
Yes!

**Comment by tomas-salgado** [comment]
Hey @reaganrazon! Are you still working on this issue? No worries if not, just lmk so I can open it up for someone else!

**Comment by tomas-salgado** [comment]
@wflore19 could you comment on this issue so that I can assign it to you?

**Comment by wflore19** [comment]
I'll work on this✋
