### ISSUE TITLE
Ability to edit a resource's attachment 🔗

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#262]
### Description

Currently, a member can post a resource with an attachment, but can't edit the attachment after. This issue should introduce the ability to do so.

### Acceptance Criteria

When a member (who posted a file-based resource) clicks edit, it should show the attachment field. They should be able to see the already uploaded file, and they should also be able to upload a different file. If they choose a different file, then any previous files should be deleted both in the database and from cloud storage.

### Additional Context

Here is the [`ResourceAttachmentField`](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/shared/components/resource-form.tsx#L52), which controls the file input.

**Comment by BeteabTefera** [comment]
@ramiAbdou would love to take this on:)

**Comment by arelymartinez16** [comment]
I would like to work on this :)

**Comment by tomas-salgado** [comment]
@arelymartinez16 all yours!
