### ISSUE TITLE
Update filtering UX (tags, my upvotes, better search) 🔎

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#263]
More context coming soon...

**Comment by ramiAbdou** [comment]
cc: @tomas-salgado let's add a description at our next sync!

**Comment by rafa1510** [comment]
Hello,can I work on this?

**Comment by tomas-salgado** [comment]
Hey @rafa1510, we actually won't be moving forward with this issue as originally planned, so going to close this one

**Comment by tomas-salgado** [comment]
Hey @rafa1510, we actually won't be moving forward with this issue as originally planned, so going to close this one
