### ISSUE TITLE
Implement a more UX-friendly file uploader 🗂️

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#264]
### Description

The existing file uploader is a simple HTML `<input type="file" />` with no styling applied to it. It looks like this:

![Screenshot 2024-05-28 at 8 53 13 PM](https://github.com/colorstackorg/oyster/assets/38056800/ce3a3b6b-29af-466a-8b4f-bfd2476e5db7)

This is obviously below the standard for good UI/UX experiences of a UI input.

What we'd like to get to is something more modern such as this:

![Screenshot 2024-05-28 at 8 55 19 PM](https://github.com/colorstackorg/oyster/assets/38056800/a383b81b-b8e3-4864-8b40-70e5c01be64e)

### Acceptance Criteria

This issue should:
- Implement a new `FileUploader` component in our [`ui`](https://github.com/colorstackorg/oyster/tree/9b8d42f52cb8ce21adf2148efe8b7b33121648cc/packages/ui) package with a more modern UX such as the image above.
- Use that `<FileUploader />` in the [`ResourceAttachmentField`](https://github.com/colorstackorg/oyster/tree/main/apps/member-profile/app/shared/components#L71).

**Comment by BeteabTefera** [comment]
@ramiAbdou while I wait for the slack notification issues with context I will take this one it could be a useful challenge to repolish my frontend skills

**Comment by ramiAbdou** [comment]
Going to try to limit assigning more than 2 tickets at once per person, but if you get the other 2 done and this ticket still isn't taken, let me know if you want to work on it!

**Comment by wflore19** [comment]
I can work on this
