### ISSUE TITLE
Send daily Slack notification for new resources posted 📣

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#265]
### Description

In order to keep members in the loop about new resources and keep the Resource Database top of mind (which can help with feature adoption), we should send a daily notification of all the latest resources that were posted.

### Acceptance Criteria

Every day at 9 AM PT, we should send a message to a Slack channel (TBD on which one it will be), which sends a list of all the resources that were posted in the last 24 hours. The message should look something like this:

```
Some new resources were posted in the Resource Database:
- [Title of Resource] by @SlackUser1
- [Title of Resource] by @SlackUser2
- [Title of Resource] by @SlackUser3

Check out these latest resources [here](/link-to-resource-database-with-filter-for-last-24-hours)!

Show some love if any of these are helpful!
```

Note: If there were no resources posted in the last 24 hours, we shouldn't send the notification.

### Additional Context

This should be implemented as a Bull job, similar to the [birthday notifications](https://github.com/colorstackorg/oyster/blob/ba2e91c5d27303f3b5414ec79ef154806c8218d1/packages/core/src/modules/member/use-cases/send-birthday-notification.ts#L8).

**Comment by BeteabTefera** [comment]
@ramiAbdou would love to take this on:) looks like its similar to https://github.com/colorstackorg/oyster/issues/265 that is assigned to me

**Comment by ramiAbdou** [comment]
@BeteabTefera sorry for the delay, but just updated the issue description!

**Comment by tomas-salgado** [comment]
Going to open up this issue!

**Comment by Hamza-Mos** [comment]
i call dibs
