### ISSUE TITLE
Add confirmation that user has searched for duplicate resources 🔎

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#269]
### Description

There have already been a couple of duplicate resources posted in the community. Sometimes, they're the exact same URL and sometimes, they're similar URLs but not exactly the same. We are already adding manual reporting from the community to mark certain resources as duplicates (#270), but we can take one more step to prevent this.

Duplicate resources can be prevented by doing a simple check for that resource.

### Acceptance Criteria

In the "Add Resource" form, we should add a checkbox field above the "Title" field, which says something to the effect:

```
I have searched for this resource and confirm that it doesn't exist.
```

This should be a required field, so the user can't submit the resource without it.

### Additional Context

Here is the current "Add Resource" form:

![Screenshot 2024-06-04 at 3 31 36 PM](https://github.com/colorstackorg/oyster/assets/38056800/ffa7012c-04ed-407f-8e95-0b00ed2ee637)

Here is a similar implementation of the checkbox:

https://github.com/colorstackorg/oyster/blob/ba2e91c5d27303f3b5414ec79ef154806c8218d1/apps/member-profile/app/routes/_public.apply._index.tsx#L165

**Comment by reaganrazon** [comment]
I would be interested in this one

**Comment by ramiAbdou** [comment]
It's yours @reaganrazon! Check back by EOD tomorrow for some extra context on this issue!

**Comment by ramiAbdou** [comment]
Hey @reaganrazon, sorry for the delay here! I actually changed the nature of this issue a bit, but it should be solving the same problem. Take a look at the updated description and let me know if it makes sense to you! Happy to provide more context wherever is needed.

**Comment by reaganrazon** [comment]
I'm almost ready for review on this! Just as an update.

**Comment by tomas-salgado** [comment]
@reaganrazon are you still working on this issue? No worries if not, I'll just open up the issue

**Comment by gxsoto** [comment]
I'd like to work on this!

**Comment by tomas-salgado** [comment]
@gxsoto are you still working on this issues? No worries if not, looking to open this one up

**Comment by gxsoto** [comment]
Ah, no I haven't been able to keep up with this issue, feel free to open it up for someone else to take it on!

**Comment by AbdulmajeedKabala** [comment]
I would like to take on this issue!

**Comment by aphillips123** [comment]
I would like to take thiis!

**Comment by tomas-salgado** [comment]
Assigning @AbdulmajeedKabala! @aphillips123 I just chatted with @ciaracade we can reassign you to #266
