### ISSUE TITLE
Search isn't reset after creating resource tag 🔎

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#272]
### Description

After creating a tag for a resource, the dropdown that is supposed to show all available tags is only showing the tag that just got created because the search value is not being reset under the hood (though in the UI it seems to be reset).

### Steps to Reproduce

1. Go to `/resources/add` to add a resource.
2. Create/select a new tag.
3. The newly created tag is the only one that appears in the dropdown.

### Expected Behavior

After creating a tag, the search should truly reset and the dropdown should show all options as if there was an empty search value.

### Screenshots

https://github.com/colorstackorg/oyster/assets/38056800/6997b16c-8e7f-434d-8267-9391f8ef5dd8

### Additional Context

A good place to start with this is the [`ResourceTagsField`](https://github.com/colorstackorg/oyster/blob/ba2e91c5d27303f3b5414ec79ef154806c8218d1/apps/member-profile/app/shared/components/resource-form.tsx#L131).

**Comment by AshleyJagai** [comment]
Hello! I would like to tackle issue #272 :)

**Comment by ramiAbdou** [comment]
You got it, @AshleyJagai!

**Comment by tomas-salgado** [comment]
Going to open up this issue!

**Comment by iperalta7** [comment]
I'd like to take this on :)

**Comment by tomas-salgado** [comment]
@iperalta7 you've got it!
