### ISSUE TITLE
Companies (v1) 💼

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#296]
### Description

A core part of a member's experience is finding the right company to work for. There are obviously tools out there to find companies to work for, but ColorStack is uniquely positioned to have a database of companies because of our members' unique experiences. Not only can members search for companies, they'll be able to see unique information such as company reviews from other members, how many people work at a company, a community "rating" for the company, and more!

### Acceptance Criteria

Here is what will be included in the v1:
- [x] A top-level "Companies" tab in the Member Profile.
- [x] The ability to search for companies by name. Only companies that have a review or someone that has worked there should show up in the list, which should appear as cards.
- [x] A company card, which includes:
  - [x] Name
  - [x] Description
  - [x] Logo
  - [x] # of ColorStack members who currently work there.
  - [x] # of reviews that the company has.
  - [x] A ColorStack rating.
- [x] The ability to add a company review, which consists of:
  - [x] An associated work experience.
  - [x] An overall rating out of 10.
  - [x] "Would you recommend a ColorStack member to work here?"
  - [x] A long-text box for the review with a minimum character count of 1,000 characters.
- [x] The ability to edit a company review.
- [ ] A "Company" page, which consists of:
  - [x] Name
  - [x] Description
  - [x] Website
  - [x] Count of reviews.
  - [x] List of reviews.
  - [x] A ColorStack rating.
  - [x] # of ColorStack members who _currently_ work there.
  - [x] List of members who _currently_ work there.
  - [ ] Other links (ie: levels.fyi, LeetCode tagged questions, Slack channel).
  - [ ] Any Fam Friday recordings from that company.
  - [ ] Associated resources.
- [x] Gamification - members receive points for submitting a company review.

Will likely need to do a general cleanup of the "companies" SQL table as well as the ability to edit company information, logo, etc by admins.

**Comment by reaganrazon** [comment]
This is going to be really cool!
