### ISSUE TITLE
Ability to post anonymous company review 👻 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#302]
### Description

Members should have the ability to post a company review anonymously. On the Companies page, on the modal that appears after pressing "Add Review", there should be a checkbox with a description that specifies when selected, review will be posted anonymously. The default should not be anonymous posting, but this feature will allow members to opt into anonymously reviewing if they prefer. 

### Acceptance Criteria

- [ ] Add a BOOLEAN column `anonymous` to the database table `company_review` through a database migration. The default of `anonymous` should be `false`
- [ ] On the "Add Review" modal [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/shared/components/review-form.tsx), include a checkbox with a description 
- [ ] The state of this checkbox should reflect the current `anonymous` value for the review (checked if true)
- [ ] Update the `anonymous` column in the database when the checkbox is toggled.
- [ ] When company reviews are displayed, if `anonymous` for a given review is `true`, the name for the reviewer should be "Anonymous", and there should be a blank profile picture

### Additional Context

Check out the `checkbox` component [here](https://github.com/colorstackorg/oyster/blob/main/packages/ui/src/components/checkbox.tsx#L22-L79), and see examples of database migrations [here!](https://github.com/colorstackorg/oyster/tree/main/packages/db/src/migrations)
Feel free to add or ask for any more insight!

**Comment by farouqalsalih** [comment]
Hey, I'll get to work on this issue

**Comment by tomas-salgado** [comment]
Going to open up this issue!

**Comment by jasonappah** [comment]
Can I take this issue?

**Comment by tomas-salgado** [comment]
@jasonappah you've got it!
