### ISSUE TITLE
Modal on Companies Page 📃 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#314]
### Description
See #316 for project overview. Note that this issue is dependent on a function implemented in #313.

If a member does not yet have access to the Companies page, when they go to the Companies page there should be a modal that appears that specifies why they don’t have access to reviews yet. 

### Acceptance Criteria

Within the [loader function](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies.tsx#L48-L108) for the Companies page, use the function `hasReviewsAccess` (implemented in issue #313) to check if user has access. 

If user does not have access, a modal should appear with the title “Oops! You missed a step”, and the following description: “To view company reviews, you must first add a review of one of your experiences. You can do so here!”, where the word “here” links users to the member profile page at “/profile/work” where they can add a review. 

### Additional Context

Take a look through the codebase to see various examples and implementations of Modals!

**Comment by ciaracade** [comment]
🙋🏽‍♀️

**Comment by tomas-salgado** [comment]
@ciaracade are you still working on this? all good if not, I'll just open up the issue

**Comment by rafa1510** [comment]
Hey! Can I work on this?

**Comment by ciaracade** [comment]
Take it away! So many things came up for me  :(
