### ISSUE TITLE
"This was helpful" button 👍 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#317]
### Description

For every review, add a button in the top right corner with the description “That was helpful” followed by the count of users that have pressed that button. 

<img src="https://github.com/colorstackorg/oyster/assets/91388965/cfd59029-8ba0-4a4d-80c8-69b414c93c3d" alt="this_was_helpful" width="600"/>

### Acceptance Criteria

Backend: Store the count of “upvotes” in the `company_reviews` database table. This will require adding an `upvotes` field through a database migration. See [here](https://github.com/colorstackorg/oyster/blob/main/docs/how-to-implement-a-database-migration.md).

Frontend: This will require building a button with a different UX for different states: 

Default:
<img src="https://github.com/colorstackorg/oyster/assets/91388965/a7f84d25-2c77-42b7-98d9-a1df3b6b3417" alt="Screenshot 2024-06-19 at 11 54 32 AM" width="200"/>

When hovering: 
<img src="https://github.com/colorstackorg/oyster/assets/91388965/ade0e857-af6c-4c52-8666-b059ba8b1c5c" alt="Screenshot 2024-06-19 at 11 55 02 AM" width="200"/>

When pressed: 
<img src="https://github.com/colorstackorg/oyster/assets/91388965/2df21165-85aa-48d8-9f4a-515ffd0f697c" alt="Screenshot 2024-06-19 at 11 55 32 AM" width="200"/>

Note that this has the same coloring and logic as the upvote button for Resources, which can be seen [here](https://github.com/colorstackorg/oyster/blob/5bb1dc853523c8bd726a9456096458076ccbda92/apps/member-profile/app/routes/_profile.resources.tsx#L470-L497).

This also requires retrieving ‘upvotes’ count for each review from database on [list-company-reviews.ts](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/employment/queries/list-company-reviews.ts). This is necessary to have each review display its individual count for “upvotes”. As an example, see how this is done on the Resources page through the loader function in [app/routes/_profile.resources.tsx](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.resources.tsx)

**Comment by jessherlitz** [comment]
Hi Tomas, could I work on this issue? Thank you.

**Comment by tomas-salgado** [comment]
@jessherlitz you've got it!
