### ISSUE TITLE
Improve Editing UX 🖌️ 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#318]
### Description
This issue is dependent on #317.

Currently company reviews can only be edited from the Work History tab within “Profile”. We want to have the ability to edit reviews directly from Companies page. 

<img src="https://github.com/colorstackorg/oyster/assets/91388965/c88f32ae-0322-4541-8483-ed7d10192471" alt="editing-ux" width="600"/>

### Acceptance Criteria

When a user navigates to their own reviews within the Companies page, they are able to see an edit icon in the top right corner of the their review, just below the like button that is being implemented in issue #317. Additionally, there should be a tooltip such that when hover over the edit icon, the words “Edit Review” appear (see an example [here](https://github.com/colorstackorg/oyster/blob/5bb1dc853523c8bd726a9456096458076ccbda92/apps/member-profile/app/routes/_profile.resources.tsx#L573-L588)).  

The edit icon should only appears for given user’s reviews, and not anyone else’s. 

When user presses the edit icon, this should lead to the module [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.profile.work.$id.review.edit.tsx) (the same one used when editing reviews from the “Profile” tab). 

### Additional Context 

Since there already is a module that gives the ability to editing reviews, this issue is just about adding a button that links to this module within the “Companies” page. Also, it’s essential to add a condition such that this edit icon is only visible for the user that wrote that particular review. 

When creating the button itself, use the Link react component (see an example [here](https://github.com/colorstackorg/oyster/blob/5bb1dc853523c8bd726a9456096458076ccbda92/apps/member-profile/app/routes/_profile.resources.tsx#L575-L583)).

**Comment by wflore19** [comment]
Hey Tomas, I can take on this issue.
