### ISSUE TITLE
Add 'levels_fyi' field to database 📖 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#319]
### Description

The company name used in the levels_fyi URL of a page is not always clear (i.e. JPMorgan is `jpmorgan-chase`), so we need to store the levels_fyi URL name in a database field. 

### Acceptance Criteria

Add a field named `levels_fyi` to the `companies` by implementing a database migration. 

### Additional Context

See documentation for creating a database migration [here](how-to-implement-a-database-migration.md), and see various examples of migrations in the [migrations](https://github.com/colorstackorg/oyster/tree/main/packages/db/src/migrations) folder! This is where the new migration will be stored.

**Comment by lianarosa** [comment]
I'm interested in working on this issue!

**Comment by tomas-salgado** [comment]
@lianarosa All yours!
