### ISSUE TITLE
Add Levels.fyi to company pages 💸 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#320]
### Description

To help members more easily access information regarding salary for each company, we want to include a link to the [Levels.fyi](http://levels.fyi/) salary page of each company on their company page.

<img src="https://github.com/colorstackorg/oyster/assets/91388965/badd6c61-c16d-4759-b4fd-c313e3e5c7b8" alt="levels1" width="600"/>

### Acceptance Criteria

Add a `levels_fyi` field to the `companies` table in the database. This can be done through a database migration. 

Add the following Levels.fyi logo to the [images](https://github.com/colorstackorg/oyster/tree/main/apps/member-profile/public/images) folder: 

<img src="https://github.com/colorstackorg/oyster/assets/91388965/48a5aec4-d5ca-44bd-8385-36ec17413d6b" alt="levels_logo" width="100"/>

Then, when loading the frontend for each company page (which is done in the loader function [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies_.%24id.tsx#L35), check the `companies` table for a non-null value for `levels_fyi` (which was added issue # !). If there is no `levels_fyi` value, do nothing (no Levels.fyi logo should appear on the UI). Otherwise, have the Levels.fyi logo appear underneath the link to the company page. 

The logo should be a link to the page [https://www.levels.fyi/companies/<levels_fyi_field_value>/salaries](https://www.levels.fyi/companies/google/salaries). Implement this link with a tooltip, such that when hovering over the logo, the words 'View Salary Information on Levels.fyi' appear (see an example of a tooltip implementation [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies.tsx#L259)).

**Comment by wflore19** [comment]
This is my first open source contribution but I'm interested in working on this feature. 

Do I need to wait for database PR ['add levels_fyi field to companies database' #330](https://github.com/colorstackorg/oyster/pull/330) to go through first? I am not seeing the correct type/interface in the ```packages/db/dist/db.d.ts``` file and I'm getting this error when I add the argument 'companies.levels_fyi' to the select property in the getCompany() query function.

**Comment by tomas-salgado** [comment]
You've got it @wflore19!

Yeah, technically #330 needs to be merged and pulled into your local before you'll see a levels_fyi field appear, but in the meantime feel free to ignore this error and just continue with the rest. 
Or, if you'd like, you can just manually add the migration in @lianarosa's PR [here](https://github.com/colorstackorg/oyster/pull/330/files) to your local, run `yarn db:migrate`, and then that should add the `levels.fyi` field to your local database.

**Comment by wflore19** [comment]
Sounds good I'll try to get running with what Liana has done. Thanks.
