### ISSUE TITLE
Applications in Admin Dashboard should be shown oldest first 🔼

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#33]
Currently, applications in the Admin Dashboard are shown newest to oldest, but though that means some applications will get reviewed really fast, it also means that some applications will get reviewed fairly slow. To have a more consistent time to review each application, we'll sort oldest to newest.

[This](https://github.com/colorstackorg/oyster/blob/main/apps/admin-dashboard/app/routes/_dashboard.applications.tsx) is the route where the applications get displayed, and [this](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/application/queries/list-applications.ts#L16) is the function that gets called, which pulls applications from the database.  You'll want to update the [`orderBy()`](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/application/queries/list-applications.ts#L55) statement to go the other way. 🔼

**Comment by ramiAbdou** [comment]
Note: Boris reached out to me about this, so I'm saving this ticket for him!

**Comment by Boris713** [comment]
On it!!

**Comment by ramiAbdou** [comment]
It's all yours, @Boris713!
