### ISSUE TITLE
Sort `CONTRIBUTORS.yml` automatically using bot 🤖

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#34]
### Description

When members add their GitHub username to the `CONTRIBUTORS.yml` file, most people will simply add their name to the end of the file. Ideally, we would like to sort all of the usernames, and do so automatically.

### Acceptance Criteria

When a new push to the `main` branches happens:
- If the `CONTRIBUTORS.yml` is already sorted, then nothing should happen.
- If the `CONTRIBUTORS.yml` is not already sorted, then it should automatically sort the the file and push a new commit.

### Example

A good example of how to do this can be found [here](https://github.com/remix-run/remix/blob/main/.github/workflows/format.yml).  Though there's a lot more going on in this file than we specifically need, we can take inspiration from how they sort a file and push a new commit.

**Comment by NK-Debrah** [comment]
I would love to work on this issue!

**Comment by ramiAbdou** [comment]
Let's go, @NK-Debrah! It's all yours!

**Comment by NK-Debrah** [comment]
I was able to create a job within the GitHub workflow to sort the contributions However, there is one minor issue though. We would need to set up GitHub credentials to allow commits to happen on the main branch. Is there a bot on the GitHub repo that we could use to make commits to the main or potentially add your credentials (since you have permissions to push on main)

```yml
- name: Commit sorted CONTRIBUTORS.yml
  if: steps.check-sorted.outputs.sorted == 'false'
  run: |
    git config --global user.email "GITHUB@EMAIL"
    git config --global user.name "GITHUB USERNAME"
    git add CONTRIBUTORS.yml
    git commit -m "chore: sort CONTRIBUTORS.yml"
    git push origin HEAD:main -f
```

**Comment by ramiAbdou** [comment]
Thank you for the exploration! We don't currently have a bot that can commit to the repo, but I'm happy to set one up. Can you point me to some GitHub documentation or examples on how to do so?

**Comment by ramiAbdou** [comment]
Now that we've had 30 or so people add their name to the `CONTRIBUTORS.yml` file, I think it's actually okay to leave the order as is. It's actually quite nice to see the order of when people signed their name.

Sorry about the lack of conviction here, but going to close this issue. Appreciate all the effort here regardless!
