### ISSUE TITLE
Allow Canadian addresses for swag pack 🇨🇦

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#342]
### Description

SwagUp now supports orders to Canadian addresses, and so we can change the [address component](https://github.com/colorstackorg/oyster/blob/main/packages/ui/src/components/address.tsx) to support Canadian addresses. Currently, only US states are supported, so this will require adding a field for selecting country, and modifying the states field to render Canadian provinces instead of states when appropriate. 

This will also require updating the swag pack form so that we display the new field for country and pass in this field to the backend. 

### Acceptance Criteria

- Modify the address component to have a ``Country`` field that gives either ``US`` or ``CA`` as options. 
- Add `CA_PROVINCES` constant to address component using official abbreviations for provinces. We can use the information from [this](https://en.wikipedia.org/wiki/Canadian_postal_abbreviations_for_provinces_and_territories) page for the correct provinces and abbreviations.

- Update the address component to dynamically display values from ``USA_STATES`` or ``CA_PROVINCES`` depending on the selected country.

- Update Swag Pack form [here](https://github.com/tomas-salgado/oyster/blob/fb47487b133862e5dac841b1bcc88dffe803d758/apps/member-profile/app/routes/_profile.home.claim-swag-pack._index.tsx) to have a field for selecting country and to render states or provinces depending on what is selected for countries.

- Add ``addressCountry`` field to `student` database table with a database migration script (see how to do that [here!](https://github.com/colorstackorg/oyster/blob/main/docs/how-to-implement-a-database-migration.md))

- Update [claimSwagPack](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/swag-pack/use-cases/claim-swag-pack.ts) and [orderSwagPack](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/swag-pack/swag-pack.service.ts) to pass in country

**Comment by JustinhSE** [comment]
I would be interested in this, however, is there a description? @ramiAbdou

**Comment by ramiAbdou** [comment]
Meeting w/ @tomas-salgado today, we'll discuss the issue and there should be a description later this week!

**Comment by jessherlitz** [comment]
If @JustinhSE doesn't want to work on this, I'll take it! 😄
