### ISSUE TITLE
Add GitHub as social link in the Member Profile home page 🏡 

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#37]
### Description

We display our ColorStack socials in the home page of the Member Profile, as such:

![Screenshot 2024-03-29 at 8 44 03 AM](https://github.com/colorstackorg/oyster/assets/38056800/1e436bf8-44f6-4f52-963f-3c65a19aa90b)

Now that we are open-source, we should have the link to this GitHub repository.

### Acceptance Criteria

We should display the GitHub logo just after our `Twitter` logo.

### Additional Context

Note that we use `react-feather`, which is an icon library where we get our social logos from.

**Comment by vazquezea96** [comment]
I would love to work on this issue!

**Comment by ramiAbdou** [comment]
It's all yours, @vazquezea96! 🥳

**Comment by domenic21** [comment]
> I would love to work on this issue!

not If I do it first lol
