### ISSUE TITLE
Explore `pnpm` as package manager over `yarn` 📦

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#39]
This is an open issue meant to explore the best package manager. So far, it looks like `pnpm` is the most promising with regards to its first-class monorepo support as well as installation speed. But that is certainly up in the air.

Learnings will be documented below!

**Comment by ramipellumbi** [comment]
Definitely better than yarn! In our org monorepo the difference in install time is seconds vs. minutes! It is just so seamless with turbo. I can explore this / open a PR for the transition for you to review after the eslint and husky one.

**Comment by ramipellumbi** [comment]
I am maybe 60% through this one. Some notes that pnpm makes you be more careful with (which I think is better):

- You use `dotenv` in packages that don't actually have `dotenv` as a dependency. This gets fixed for `pnpm` to function as desired. This was in `packages/db` and `packages/core`
- In `packages/email-templates`, you don't have a dependency on `@types/react`. This is not portable and a type annotation is necessary.
- The following packages used `zod` but did not have a dependency on `zod`: `packages/core`

Will update with more things I am changing as I find them

**Comment by ramiAbdou** [comment]
So this weekend I got to play around with [Bun](https://bun.sh) a bit more and it was an incredible experience. Aside from Bun being incredibly fast as a package manager, I'm now sold by their all-in-one tooling kit (ie: package manager, runtime, test runner, bundler, etc). Everything is just lightning quick across the board. I'm pretty confident that we'll end up going with Bun.

If you have any other learnings from the `pnpm` work that you started, let me know (feel free to share a branch) as it'll likely still be relevant. Sorry about any inconvenience here Rami!

**Comment by ramiAbdou** [comment]
Closing as we'll be proceeding with Bun.
