### ISSUE TITLE
feat: improve search logic to include description 🔎 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#464]
### Description

Currently on the [Resources](https://app.colorstack.io/resources?search=) page, the search bar only has logic that tries to match the search query with the title of resources. We want to expand this to also compare the description of the resource to the search query. 

### Acceptance Criteria

Expand upon the search logic so that the search query also compares the description with both `ilike` and `word_similarity` operations. 

### Additional Context

The search logic is implemented [here](https://github.com/colorstackorg/oyster/blob/3bc659483dd64f13c533fb40ef608a39af333262/packages/core/src/modules/resource/queries/list-resources.ts#L56-L61). Note that `resources` also has a database field titled `description`.

**Comment by gpolite0** [comment]
@tomas-salgado I can take a look at this

**Comment by tomas-salgado** [comment]
@gpolite0 you've got it!
