### ISSUE TITLE
Bug: Ethnicities dropdown is too small

### ISSUE THREAD

**Issue by gpolite0** [colorstackorg/oyster#468]
### Description

When you go to select your ethnicity on the profile, the dropdown only shows two countries at a time, making it hard to scroll through the options, and some of the countries towards the end of the alphabet get cut off.

### Steps to Reproduce

1. Go to Profile > Personal
2. Scroll down to Ethnicities
3. Notice how you can only view 2 countries at once and some of the countries get cut off

### Expected Behavior

See more than 2 countries at once

### Screenshots

<img width="1470" alt="Screenshot 2024-08-23 at 2 29 28 AM" src="https://github.com/user-attachments/assets/d5a1e332-8524-4df4-888a-6cbe9b55cc9f">

**Comment by Habeebah157** [comment]
Can I take this?

**Comment by gxsoto** [comment]
I'd be open to working on this 👀

**Comment by tomas-salgado** [comment]
@gxsoto you've got it!
