### ISSUE TITLE
Add/Edit Phone Numbers in Member Profile 🔢 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#471]
### Description

We want to implement the ability to add/edit phone numbers from the Member Profile. Specifically, this should appear as a field under `/profile/general`. 

### Acceptance Criteria

To implement this issue, the following is required:
- add a field `phone_number` to the database
- add a new field to `/profile/general` after the field `CurrentLocationField` [here](https://github.com/colorstackorg/oyster/blob/4b27f72c1841f32b454c2d3d0a1e5149de4b818b/apps/member-profile/app/routes/_profile.profile.general.tsx#L175)
- verify that the value entered in the field is a 10-digit `int`

### Additional Context

You can add a new field to the database using a database migration. See the [docs](https://github.com/colorstackorg/oyster/blob/main/docs/how-to-implement-a-database-migration.md)!

Note that this will also require updating the loader and action functions within [this](https://github.com/colorstackorg/oyster/blob/4b27f72c1841f32b454c2d3d0a1e5149de4b818b/apps/member-profile/app/routes/_profile.profile.general.tsx) file to ensure that any previously entered number is properly loaded, and any added/edited phone number is updated.

**Comment by Hamza-Mos** [comment]
@tomas-salgado can you assign this to moi?
