### ISSUE TITLE
Bulk Text Notifications 📱 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#473]
### Description

We want to add the infrastructure to be able to send bulk text notifications to members. 

### Acceptance Criteria

There are two main parts to implementing this: 

- [x] #471
- [x] #472

After these issues are implemented, there will be functionality for members to add their phone numbers. Then, when we want to send a mass text notification, we can pass in all the added phone numbers to the new job and then utilize Twilio to send texts to all those numbers.

**Comment by imnotrafa** [comment]
I would like to take on this project!

**Comment by tomas-salgado** [comment]
@imnotrafa this project is actually divided up into separate issues, so only those issues can be assigned
