### ISSUE TITLE
Send "ColorStack Anniversary" notification 🥳 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#474]
### Description

We want to send an email notification to members on their ColorStack Anniversary! 

### Acceptance Criteria

- implement a function that extracts the field `acceptedAt` in the `students` table for all members
- determine which members have an anniversary on the current day (current as in the date the job is ran)
- send an email notification that states how many years the given member has been a ColorStack member
- register the job to the daily worker [here](https://github.com/colorstackorg/oyster/blob/9df7e9191aa29437accac98a62623866841903a4/packages/core/src/modules/member/member.worker.ts)

### Additional Context

Check out how the birthday notifications are implemented [here](https://github.com/colorstackorg/oyster/blob/d3e8a23496aab0bb99d64826cafa6e1998fadb3d/packages/core/src/modules/member/use-cases/send-birthday-notification.ts) for an example of implementing a somewhat similar job. 

We will also want to add the code for this anniversary job within `packages/core/src/modules/member/use-cases/`.

**Comment by katlj** [comment]
I would like to work on this ticket!

**Comment by ciaracade** [comment]
Wondering if this ticket is still being work on? I'd love to take this on.

**Comment by katlj** [comment]
Yeah you can take it, been swamped with school

**Comment by ciaracade** [comment]
I saw that someone implemented a git workflow that automatically checks the status of an issue, so I wanted to give an update so i won't get kicked off lol. Still doing this issue + it goes hand in hand with my Bloomberg issue [#535](https://github.com/colorstackorg/oyster/issues/535)

**Comment by tomas-salgado** [comment]
Sounds good!
