### ISSUE TITLE
Store Directory Profile URLs on Slack Profiles 🔗 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#497]
### Description

We would like to be able to link each member's directory profile URL within their Slack profile. This will require implementing a function that retrieves all of the members with both Slack profiles and member directory profiles, and then passing in the member's directory URL as a new field in the Slack profiles. 

### Acceptance Criteria
- Retrieve all members with both Slack profiles (check `joined_slack_at` in `students` table) and member directory profiles (check `joined_member_directory_at` in `students` table)
- Generate the URL for each directory profile using the member ID 
- Store this URL into the Slack profile for each member
- Abide by any rate-limiting that Slack has (since this function will modify a large number of Slack profiles)

### Additional Context

We can see how the URL is generated for each directory profile [here](https://github.com/tomas-salgado/oyster/blob/1da5d3dc2035c29a94ab88c5d339966edb04c4cb/apps/member-profile/app/routes/_profile.directory.tsx#L464). Note that `generatePath` is a deterministic function, meaning that given a particular input (i.e. a member ID), the URL produced by this function will always be the same. 

Check the Slack documentation [here](https://api.slack.com/methods/users.profile.set). There is an example in the codebase of utilizing the Slack API to modify a Slack profile [here](https://github.com/tomas-salgado/oyster/blob/1da5d3dc2035c29a94ab88c5d339966edb04c4cb/packages/core/src/modules/slack/services/slack-user.service.ts#L31-L37). 

Don't worry about actually running this function-this will be done manually once the function is implemented!

**Comment by savazques** [comment]
Can I work on this?

**Comment by tomas-salgado** [comment]
Yes!

**Comment by ejcleary** [comment]
Is this still being worked on? If not I'd love to take it on
