### ISSUE TITLE
Scrollbars show on everywhere on Windows

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#5]
### Description

On Windows machines, it seems like scrollbars show everywhere in the Member Profile as well as the Admin Dashboard. It looks really ugly!

### Steps to Reproduce

1. Be on a Windows machine.
2. Go to Member Profile.
3. See scrollbars.

### Expected Behavior

The scrollbars should be hidden, and only appear once the scrolling happens (such as the default behavior on MacOS).

### Screenshots

![Ugly Scrollbar (1:2)](https://github.com/colorstackorg/oyster/assets/38056800/09d6c442-1349-4e9a-a805-37a8e8128426)
![Ugly Scrollbar (2:2)](https://github.com/colorstackorg/oyster/assets/38056800/ea284de5-b8ef-4b57-9d5f-a75630ce3440)

### Additional Context

You need to be on a Windows machine to reproduce!

**Comment by ramiAbdou** [comment]
We have a shared CSS file that is applied in all of our frontend applications, which can be found [here](https://github.com/colorstackorg/oyster/blob/v1.0.0/packages/core-ui/src/css/shared.css). You'll likely need to add some CSS to this file that disables scrollbars on Windows!

**Comment by ayoaru** [comment]
I'm gonna try and take a look when I can! -Shola

**Comment by ramiAbdou** [comment]
Thank you so much, @ayoaru! This one has been really hard me to track down without a Windows machine. Happy to help however I can though!

**Comment by ayoaru** [comment]
Just a quick note, I haven't forgotten about this and just got caught up with some end of the year projects. I should be able to tackle this sometime next week (week of 4/21)

**Comment by BeteabTefera** [comment]
@ayoaru if you haven't started on it i can take a stab at it and send updates as well lmk if you need help

**Comment by ayoaru** [comment]
@BeteabTefera Great timing, I just pulled up VSCode and was about to try something. Will let you know the outcome momentarily

**Comment by BeteabTefera** [comment]
Sounds good, I have yet to read the [contributing guideline](https://github.com/colorstackorg/oyster/blob/ad5493c4dafd06af02f78ca703fed0e722d4e4a4/CONTRIBUTING.md) and once i am done and set up my local environment, I can assist with anything : )

**Comment by ayoaru** [comment]
@BeteabTefera solved it! Opening a PR in a bit
