### ISSUE TITLE
Pinecone API key needed for Oyster's API to run correctly

### ISSUE THREAD

**Issue by rafa1510** [colorstackorg/oyster#505]
### Description

If a Pinecone API key is not provided on the `.env` file under the `api` folder, then the application throws an error.

### Steps to Reproduce

1. Run `yarn dev:apps` without `PINECONE_API_KEY` set to anything in the `.env` file under `api`

### Expected Behavior

Expected API to run correctly and send the `console.log` message 'API is up and running! 🚀'

### Screenshots

Terminal error output when `PINECONE_API_KEY` isn't set:
![image](https://github.com/user-attachments/assets/dd11aade-ddc3-41b7-b486-d27529994feb)

Terminal output when `PINECONE_API_KEY` is set:
![image](https://github.com/user-attachments/assets/780c5a34-4f37-41d5-8a07-a5af5426f787)

### Additional Context

This error seems to prevent the Oyster API from functioning correctly. In my case, it didn't seem to run the BullMQ workers correctly.

**Comment by wflore19** [comment]
this was resolved in #568 I think it can be closed @tomas-salgado
