### ISSUE TITLE
Leetcode Tagged 👨‍💻 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#516]
### Description

We want to make it easier for members to access the list of Leetcode tagged questions for each company. In Issue #321, a Levels.fyi link was implemented for each company page. Here, we want to do a similar idea except instead of linking to the Levels.fyi page for the company, we'll link to a list of the leetcode tagged questions for that company. 

### Acceptance Criteria

- Add a field named leetcode_tagged to the `companies` table by implementing a database migration.
- Add the following Leetcode logo to the [images](https://github.com/colorstackorg/oyster/tree/main/apps/member-profile/public/images) folder: 

<img src="https://github.com/user-attachments/assets/58775a85-8e40-433a-be02-b3712d2f2e8b" alt="levels_logo" width="50"/>

- On each company page, we should have this Leetcode logo appear right next to the Levels.fyi logo. This should then be a link that will take you to the URL saved in that company's `leetcode_tagged` field. 
- Note that the logo should ONLY appear for companies that have a non-empty value for `leetcode_tagged`

### Additional Context
See documentation for creating a database migration [here](how-to-implement-a-database-migration.md), and see various examples of migrations in the [migrations](https://github.com/colorstackorg/oyster/tree/main/packages/db/src/migrations) folder! This is where the new migration will be stored. 

Note that for this PR you do NOT need to populate the database with the URLs for the leetcode tagged-you only need to create the field. The population will be done later. 

The implementation of this issue will have similarities to #321, so feel free to check out that issue and the relevant PRs!

Final note: We will likely use [this](https://github.com/krishnadey30/LeetCode-Questions-CompanyWise/) resource to get the lists of company-tagged Leetcode questions! Shoutout to @Wisesofthemall for sharing this resource

**Comment by tomas-salgado** [comment]
Saving this issue for Carson!

**Comment by JustinhSE** [comment]
This is dope, can’t wait to see the end result!
