### ISSUE TITLE
Unable to edit headline

### ISSUE THREAD

**Issue by aarontorres0** [colorstackorg/oyster#525]
### Description

Unable to edit `Headline` in my profile without providing a phone number. The phone number does not have an `*` so it seems to not be required.

### Steps to Reproduce

1. Go to https://app.colorstack.io/profile/general
2. Edit your `Headline` without a phone number
3. Scroll down and `Save`
4. See error: `Must be a 10-digit number.`

### Expected Behavior

Be able to change my `Headline` without also providing phone number.

### Screenshots

Not needed. Pretty straightforward.

**Comment by ramiAbdou** [comment]
Thank you so much for reporting this, @aarontorres0! Fixed this behavior in #526. Let me know if it works okay for you now!

**Comment by aarontorres0** [comment]
@ramiAbdou it works now! TY
