### ISSUE TITLE
Rejection Reason Tooltip ❌ 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#532]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

On the page ‘/profile/referrals’, members can provide ColorStack referrals. In the case that the referred individual is rejected, we want to provide the rejection reason. Members will be able to hover over the word ‘Rejected’, and then see a tooltip that describes the reason for rejection. 

### Acceptance Criteria

- Retrieve `rejection_reason` from the `applications` table
- Have this `rejection_reason` displayed as a tooltip on ‘/profile/referrals’ page in cases where referred person was rejected

### Additional Context

Take a look at where we implement this part of the UI on ‘/profile/referrals’ [here](https://github.com/colorstackorg/oyster/blob/4de42713dfee6bbfc2e07a19959d32b043e6734c/apps/member-profile/app/routes/_profile.profile.referrals.tsx#L81-L94). 

Note that to get the rejection reason into this file, we’ll have to work with the functions in [this](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/referral/referral.core.ts) file. Specifically, we want to be able to get the rejection reason for an application that has a specific `referral_id`. 

See an example of a tooltip implementation [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies.tsx#L259).

**Comment by wflore19** [comment]
I'll work on this @tomas-salgado 🙋

I had a referral fall through last week and I'm curious why
