### ISSUE TITLE
Check if AI Resume Review Tool Used 🤖 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#533]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

If a member posts their resume to the #career-resume-review channel, we want to check if they have used the AI resume review tool yet. If not, we want to send them a private message that tells them to check this out. 

### Acceptance Criteria

There is a database table `resume_book_submissions` that tracks all the resume book submissions. We want to check if there are any entries in this table that match up with the `member_id` from a specific new post in the channel. If there is a match, then we don’t want to do anything. But if there isn’t, this means this member has never used the AI Resume Tool so we want to send them a message only visible to them that informs them about the AI Resume Tool and provides a link to it. 

We want to have a job that watches the #career-resume-review channel, and runs the workflow whenever a new post appears. 

### Additional Context

Check out the function that can be used to send ephemeral slack messages [here](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/notification/use-cases/send-ephemeral-slack-notification.ts). Given a specific channel and thread, it can send a message that is visible only to a particular user. 

We have a job `slack.message.add` (see [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/apps/api/src/routers/slack.router.ts#L106-L117)) that monitors when there is a new Slack message posted. We can see an example of how that job is used [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/use-cases/add-slack-message.ts#L10-L13). This can be used to identify and execute a job when a new message is added to the #career-resume-review channel.

**Comment by rod608** [comment]
I'd like to take this on
