### ISSUE TITLE
DM members when securing the bag 🤑 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#534]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

We would like more members to update their work experiences in the member profile, and so we can prompt users to do so after they secure a new job and post about it in the channel #career-secured-the-bag. Whenever a member makes a post in #career-secured-the-bag, we want the ColorStack Bot to send them a private message with a brief message suggesting they should update their work experiences in the member profile, and a link to the work experiences page on the member profile. 

### Acceptance Criteria

- Use a job that watches the channel #career-secured-the-bag for new messages
- Extract the `userId`  to fetch a member’s `slackId`
- Use the job `notification.slack.send`  to send a message to the user

### Additional Context

Check out the function `addSlackMessage` which utilizes the job `slack.message.add` (which monitors for new slack messages) and then extracts certain values from the message and adds it to the database. For this issue, we don’t need to add anything to the database, but we do need certain values from the message. 

Search the codebase to find various usages of the job `notification.slack.send`!

Later on we’d like to integrate AI to verify that a new post in the channel is actually announcing a new job (and not some other kind of post), but this is out of the scope for this issue.

**Comment by savazques** [comment]
I'll take this one!
