### ISSUE TITLE
Update Companies page layout 📑 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#536]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

We want to improve the layout of the the page for each company with the ‘Companies’ tab (example: [Amazon’s page](https://app.colorstack.io/companies/hTVn7DlKCW1L9G0lN_z0N)). Right now, the structure of the page has all the Reviews first, and then if you scroll past all of them you can see the list of current employees and then finally the list of past employees as well. We want to improve the UX by having tabs for each of these sections. For now, we’ll have one tab for reviews, another tab for current employees, and a final tab for past employees

### Acceptance Criteria

- Modify the layout of each company page (see [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies_.%24id.tsx)) to implement separate tabs for ‘Reviews’, ‘Current Employees’, and ‘Past Employees’

### Additional Context

Check out how we use and implement tabs for the [recap](https://app.colorstack.io/recap/2024-09-21/leaderboard) page [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/apps/member-profile/app/routes/_profile.recap.%24date.tsx#L156-L174). Note that this is using a custom `RecapNavigationItem` , but for our purposes it’s fine to use just a [NavigationItem](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/shared/components/navigation.tsx).

**Comment by Wisesofthemall** [comment]
Lovinson Dieujuste Got it 🙂
