### ISSUE TITLE
Notifications to Write Company Review 💼 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#537]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

We want to encourage members to write company reviews after their work experiences have ended. To do this, we can implement and schedule a weekly job that will find all the work experiences that have ended in the last week, and then have the ColorStack bot send a private message to each of these members encouraging them to add a company review.   

### Acceptance Criteria

- Have a function that fetches the `slackId` of all students that have had a work experience end in the last week, as well as the company name of that work experience.
- Have the ColorStack bot send a DM to all of these students with a message including a link to the companies page, congratulating them on completing the work experience, and suggesting they add a review of their experience for that company.

### Additional Context

The two relevant database tables will be `students` and `workExperiences`. 

We can add the function to a new file within ‘packages/core/src/modules/employment/use-cases’. 

See [here](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/slack/use-cases/send-stackbot-mass-notification.ts) for an example of how to have the ColorStack bot send many slack DMs at once. 

See an example of a weekly job [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/member/member.worker.ts#L66-L92). Note that these jobs are scheduled with the [memberWorker](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/member/member.worker.ts#L24-L64).

**Comment by rafa1510** [comment]
I'll take this

**Comment by tomas-salgado** [comment]
Hey @rafa1510, good questions!

1. I'm going to double check with Rami on this one and get back to you later. You're right, the timeline for repeatable jobs might be done on the admin side. 
2. This is a good point. Let's do experiences that ended in the last month instead of the last week. 
3. No worries! We'll take care of this aspect of the testing.

**Comment by tomas-salgado** [comment]
@rafa1510 Yep, just checked with Rami. All we have to do is have this job implemented as a repeatable job, and then the rest of the scheduling is taken care of within the admin dashboard.

**Comment by rafa1510** [comment]
Ok perfect, just updated the PR
