### ISSUE TITLE
Add Reaction with AI Chatbot Response 🔥 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#538]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

In certain channels, we can trigger the ColorStack bot to provide a response to a question. When this occurs, we’d like for the ColorStack bot to leave a reaction to the member’s initial message, to signify that the ColorStack bot has been used here without having to go into the thread to check.  

### Acceptance Criteria

We have a function [answerChatbotQuestion](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/slack.ts#L48-L138) that answers a question in a particular channel. We want to add to this function so that after it gives a successful response, it leaves a ‘colorstack-logo’ reaction to the initial message in the thread. 

### Additional Context

To add a Slack reaction, check out the existing function [addSlackReaction](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/use-cases/add-slack-reaction.ts#L9-L41) and the worker `slack.reaction.add`.

**Comment by gxsoto** [comment]
I'd like to work on this!

**Comment by imnotrafa** [comment]
Can I take on this one?

**Comment by tomas-salgado** [comment]
@imnotrafa unfortunately not this issue, this is reserved for the students in the Bloomberg Mentorship Program for this month

**Comment by imnotrafa** [comment]
@tomas-salgado is all good. I believe the applications are closed however if thereare slots open I would like to particiapte and take on this issue.

**Comment by ayoaru** [comment]
I'll take this one!
