### ISSUE TITLE
Add AI Chatbot in Member Profile 🤖 

### ISSUE THREAD

**Issue by tomas-salgado** [colorstackorg/oyster#541]
**Issue Reserved for Bloomberg Mentorship Program**

### Description

Right now, members can ask a question to the AI Chatbot by asking the ColorStack bot within the Slack. However, we’d like for members also be able to communicate with the bot on the Member Profile. We want to create a new tab on the member profile where members can see a simple interface that allows them to write up a question, submit the question, and then get a response from the ColorStack bot. 

### Acceptance Criteria

- Create a new tab in the member directory
- Create a simple interface on the new page that has (1) a textbox for users to write their question,  (2) a button for users to submit their question, (3) a box for users to see the response from the from the chatbot, (4) a button to clear the response textbox and the question textbox to ask a new question
- Create a new function that takes a question, uses [IsQuestion](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/slack.ts#L427-L462) to verify if it is a valid question, and then uses [getAnswerFromSlackHistory](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/slack.ts#L464-L478) and [addThreadReferences](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/slack.ts#L593-L608) to return a response
- When a user presses the submit button with a non-empty message, this should trigger the new function and return a response that appears in the response textbox.
- When the button to ask a new question is pressed, the question textbox and the response textbox should be cleared.

### Additional Context

Look at the code for how we implement the chatbot service for the slack with the function [answerChatbotQuestion](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/slack.ts#L48-L138). More generally, the file [slack.ts](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/slack/slack.ts) provides a lot of functions that are relevant to understanding and implementing this issue.

**Comment by Boris713** [comment]
CALL IT
