### ISSUE TITLE
Show message on PRs if the author isn't a ColorStack member 💬

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#63]
### Description

Although this is an open-source codebase, this is primarily meant to benefit ColorStack members on their journey to become software engineers, giving them opportunities to read and contribute to the codebase.

### Acceptance Criteria

If someone opens a PR that is not a ColorStack member (we'll check if their GitHub account is connected to our database), then a GitHub Actions bot should automatically display a message like:

> It doesn't seem like you are a ColorStack member. This codebase is primarily meant to benefit our students so that they can gain experience contributing to a codebase, so unfortunately your contribution will not be prioritized.
> 
> If you are a ColorStack member, then be sure to connect your GitHub account in your [Member Profile](https://app.colorstack.io/profile/integrations)!

### Additional Context
This is dependent on #64.

**Comment by tomas-salgado** [comment]
I'd like to take this one!

**Comment by levin0710** [comment]
I can contribute to this if needed!

**Comment by ramiAbdou** [comment]
Missed this - assigning to you!
