### ISSUE TITLE
Upload event recordings in the Admin Dashboard 🎥

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#68]
### Description

After every Fam Friday, the ColorStack team uploads videos of the event sessions to YouTube! Then, it's linked in the Member Wiki. In the effort to consolidate things into one place, it would be great to be able to access event recordings from the Member Profile.

### Acceptance Criteria

An admin should be able to do the following in the Admin Dashboard:
- Go to the "Events" page.
- Click the context menu for a particular event row, which opens up a modal.
- In that modal, there should be a form that allows you to upload a link.
- When saving that form, it should save it to our database.

### Additional Context

This is the current events page in the Admin Dashboard:

![Screenshot 2024-04-01 at 6 31 15 PM](https://github.com/colorstackorg/oyster/assets/38056800/cc09ef72-4908-4e4a-89cc-65e77d99b418)

**Comment by marlon-merida** [comment]
I would like to work on this but I wont have time until the weekend, so if someone else wants it they can work on it.

**Comment by Joyeleke** [comment]
Hi Rami, just wanted to know if I could jump on this if it is ok with @marlon-merida. Had a couple questions about this feature (probably more to come in the coming days).

**Questions**

1. For the UI, do you just want an add link option right beneath the import attendees?
![events](https://github.com/colorstackorg/oyster/assets/121850312/66a9ce64-f8eb-45c4-8659-d4c7b7a28dd4)


2. For the UI, I'm also believe you want something quite similar?

![events](https://github.com/colorstackorg/oyster/assets/121850312/e9e1185d-f966-4622-99ba-cc036f6ea398)

**Comment by marlon-merida** [comment]
> Hi Rami, just wanted to know if I could jump on this if it is ok with @marlon-merida. Had a couple questions about this feature (probably more to come in the coming days).

Hi I know this is late but yes go ahead! I have been busier than aniticipated
