### ISSUE TITLE
See event recordings in the Member Profile 🎥

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#69]
### Description

After every Fam Friday, the ColorStack team uploads videos of the event sessions to YouTube! Then, it's linked in the Member Wiki. In the effort to consolidate things into one place, it would be great to be able to access event recordings from the Member Profile.

### Acceptance Criteria

To view an event recording, a member should be able to do the following in the Member Profile:
- Go to the "past events" page.
- For an individual event, a member can click a "View Event Recording" button, just below the attendee list/count. This should open the link in a new tab.

### Additional Context

This is dependent on #68 being worked on first.

**Comment by Joyeleke** [comment]
Happy to work on this since I worked on issue 68!
