### ISSUE TITLE
Enable ESLint in all applications/packages 👕

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#71]
### Description

Currently, ESLint is only enabled in the `api` application. We need to enable this in all of our other applications and packages.

### Acceptance Criteria

This issue will be accepted if:
- All apps and packages have a simple ESLint configuration the extends the base (pretty much just `eslint:recommended`) rules.
- All apps and packages have an updated `lint` commands which actually runs `eslint`.
- Any existing lint issues are fixed.

### Additional Context

The `api` already has enabled ESLint, see you can see [here](https://github.com/colorstackorg/oyster/blob/main/apps/api/.eslintrc.js) for inspiration.

**Comment by ramipellumbi** [comment]
Saw the linkedin post and had to take a peek what my name twin was up to. Awesome work! I can honestly take this issue. I have a `tooling/` I use akin to `packages/` for turborepos that includes shared prettier and eslint configurations based on if the `app` in `apps/` is a `node-server` or a `nextjs-app`. I think the repo could benefit from this, as well as setting up husky for precommit hooks (enforcing lint on all committed files) and pnpm (blows yarn out of the water on performance in the monorepo). Proposing:
- [ ] Husky configuration
- [ ] Eslint and prettier tooling common amongst all apps and packages
- [ ] Transition to pnpm

The eslint configs I use are
```
// tooling/eslint/client.js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 12,
    sourceType: "module",
  },
  plugins: ["react", "prettier", "@typescript-eslint", "import"],
  rules: {
    "no-empty-function": "off",
    "padding-line-between-statements": [
      "error",
      { blankLine: "always", prev: "*", next: "return" },
      { blankLine: "always", prev: ["const", "let", "var"], next: "*" },
      {
        blankLine: "any",
        prev: ["const", "let", "var"],
        next: ["const", "let", "var"],
      },
      { blankLine: "always", prev: "directive", next: "*" },
      { blankLine: "any", prev: "directive", next: "directive" },
      { blankLine: "always", prev: "block-like", next: "*" },
      { blankLine: "always", prev: "*", next: "block-like" },
      { blankLine: "always", prev: "*", next: "function" },
      { blankLine: "always", prev: "function", next: "*" },
    ],
    "@typescript-eslint/no-empty-function": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension": [
      1,
      {
        extensions: [".js", ".jsx", ".tsx"],
      },
    ],
    "sort-imports": [
      "error",
      {
        ignoreCase: true,
        ignoreDeclarationSort: true,
      },
    ],
    "import/order": [
      "error",
      {
        groups: [
          ["external", "builtin"],
          "internal",
          ["sibling", "parent"],
          "index",
        ],
        pathGroups: [
          {
            pattern: "@(react|next)",
            group: "external",
            position: "before",
          },
          {
            pattern: "@src/**",
            group: "internal",
          },
        ],
        pathGroupsExcludedImportTypes: ["internal", "react"],
        "newlines-between": "always",
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
  },
};
```
and
```
// tooling/eslint/server.js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["@typescript-eslint", "import"],
  rules: {
    "linebreak-style": ["error", "unix"],
    quotes: ["error", "single"],
    semi: ["error", "always"],
    "sort-imports": [
      "error",
      {
        ignoreCase: true,
        ignoreDeclarationSort: true,
      },
    ],
    "padding-line-between-statements": [
      "error",
      { blankLine: "always", prev: "*", next: "return" },
      { blankLine: "always", prev: ["const", "let", "var"], next: "*" },
      {
        blankLine: "any",
        prev: ["const", "let", "var"],
        next: ["const", "let", "var"],
      },
      { blankLine: "always", prev: "directive", next: "*" },
      { blankLine: "any", prev: "directive", next: "directive" },
      { blankLine: "always", prev: "block-like", next: "*" },
      { blankLine: "always", prev: "*", next: "block-like" },
      { blankLine: "always", prev: "*", next: "function" },
      { blankLine: "always", prev: "function", next: "*" },
    ],
    "import/order": [
      "error",
      {
        groups: [
          ["external", "builtin"],
          "internal",
          ["sibling", "parent"],
          "index",
        ],
        pathGroups: [
          {
            pattern: "@(react|next)",
            group: "external",
            position: "before",
          },
          {
            pattern: "@src/**",
            group: "internal",
          },
        ],
        pathGroupsExcludedImportTypes: ["internal", "react"],
        "newlines-between": "always",
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
  },
};
```
I can do all three tasks or just the eslint and prettier shared config. Let me know.

**Comment by ramiAbdou** [comment]
Rami, it's so good to hear from you! It's been a while my man. I really appreciate you willing to help! 🙌

I love all of your suggestions! Some immediate thoughts:
- Husky is an easy win - let's go for it! I created an issue for that [here](https://github.com/colorstackorg/oyster/issues/73).
- I'm definitely intrigued by pnpm! I haven't done a full exploration quite yet, but it seems like the best option out there for sure (barring bun haha). I actually created an [issue](https://github.com/colorstackorg/oyster/issues/39) for pnpm a few days ago, so we can separate that work out as well. A small warning in advance: since pnpm doesn't hoist dependencies in the monorepo like yarn does (I believe that's correct, but could be mistaken), I'm sure there's a probably few places where you'll need to add some missing dependencies that the yarn setup didn't care about. I can jump in wherever cause I think the PR may be bigger than initially expected. If all works out well, we'll just need to update some [documentation](https://github.com/colorstackorg/oyster/blob/main/CONTRIBUTING.md#prerequisites) that points to pnpm!
- Prettier is already standardized for the whole monorepo since the configuration it's at the [root](https://github.com/colorstackorg/oyster/blob/main/.prettierrc.js), unless you're referring to the Prettier/ESLint integration!
- For ESLint, I love your configs already! Definitely need that import ordering ASAP. 😅 I would prefer to build the ESLint config a bit more incrementally though to determine what is preferred in this codebase and to make the transition a bit smoother. I'll own the ESLint setup, but I'm definitely going to reference your examples! First I'm just going to enable the `eslint:recommended` everywhere, and then in a follow-up PR I'll work off of your extended setup. I'll likely be asking you a few questions about your config so look out!

Feel free to comment on those other issues and I'll assign them to you. Thank you so much again!

**Comment by ramipellumbi** [comment]
Got it - give me a few days but I'll get it done pretty quickly. Lot of experience with turbo at this point. You are right we will have to hoist at the minimum eslint and prettier. Unless you use prisma in a shared package or something I can't think of anything else but whatever they are it'll come up.
