### ISSUE TITLE
Husky pre-commit hooks 🐶

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#73]
### Description

[Husky](https://typicode.github.io/husky) is a tool that has Git hooks which allows to automatically do _stuff_ (ie: lint) before committing/pushing. This ensures a higher bar for code quality for anything that makes it to GitHub.

### Acceptance Criteria

We should automatically be running the `format:fix` and `lint:fix` command for any files that are staged (ie: [lint-staged](https://github.com/lint-staged/lint-staged)) before committing.

### Additional Context

We don't currently have a `format`/`format:fix` command in the codebase, so we'll need to add that first.

**Comment by ramipellumbi** [comment]
Will handle this on 4/4

**Comment by ramiAbdou** [comment]
No rush!
