### ISSUE TITLE
Query to list job offers from the database 💼

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#78]
### Description

Related to #4.

### Acceptance Criteria

The query to list job offers from the database should support pagination (ie: `limit`, `offset`) as well as the ability to filter by status, company, employment type and/or location!

**Comment by ramiAbdou** [comment]
@hebronmekuria

**Comment by imnotrafa** [comment]
Can I take on this issue?

**Comment by ramiAbdou** [comment]
Hebron is working on the v1 of the job offers feature but there might be some opportunities to work on the v2!

I'll try to put up some other feature tickets soon as well!

**Comment by imnotrafa** [comment]
Sounds good!!!

**Comment by hebronmekuria** [comment]
Can I take this on?

**Comment by hebronmekuria** [comment]
Yooo I need a little affirmation. Am I on the right track for this function? Still getting used to typescript, so I was referring to a similar file called list-events to write this. I was able to model most of my code after that file, but some portion, about introducing multiple filters was a little challenging. Idk if it's me, but I NEVER know how to find a page from a website on the codebase itself. I saw that we have our filters in the members directory, but I didn't know which file built that filtering.

<img width="1710" alt="Screenshot 2024-04-04 at 1 01 24 AM" src="https://github.com/colorstackorg/oyster/assets/70723285/a19369a9-ae38-4dc5-bc68-d3c83757ebc5">

**Comment by ramiAbdou** [comment]
Hey Hebron - yes you're on the right track. As you mentioned, the query that runs to fetch members from the directory is probably the closest to what you're doing though, so I would look at that one. You can find that code [here](https://github.com/colorstackorg/oyster/blob/2b161f7d5560ff85946d5380ec6ad1da41339776/apps/member-profile/app/routes/_profile.directory.tsx#L98)!

Regarding how to map a page from the application to the code, take a look at [this Remix documentation](https://remix.run/docs/en/main/file-conventions/routes#basic-routes) that shows you filenames in the `routes` folder map to actual URLs in the application!
