### ISSUE TITLE
Rejection email is sent after being accepted 😕

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#93]
### Description

A bit of context: we have a job that runs about 2.5 minutes after an application is received and it's responsibility is to reject a member if possible (ie: wrong graduation year, email bounced, etc).

There's an edge case where if an application is accepted within 2.5 minutes, but the job that runs after wants to reject them, it will and it will also send a rejection email (despite that the member was accepted and already invited to the community).

### Steps to Reproduce

1. Apply to the ColorStack with a bad graduation year (ie: 2023).
2. Within 2.5 minutes, accept the application in the Admin Dashboard.
3. After that 2.5 minutes has elapsed, you will get a rejection email.

### Expected Behavior

After an application is accepted, they should not get a rejected email.

### Additional Context

The [`reviewApplication`](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/application/use-cases/review-application.ts#L9) function is the one responsible for auto-rejections. We should modify this so that we only look at functions where the `status` is `pending`.

**Comment by Boris713** [comment]
Ill take this please!
