### ISSUE TITLE
Application gets "stuck" if email has already been accepted 😅

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#94]
### Description

If an application has already been accepted, and there is another application with that same email, then the process will fail if that second application is also accepted.

### Steps to Reproduce

1. Apply to ColorStack.
2. Apply to ColorStack again with the same email.
3. Accept the first application.
4. Accept the second application.
5. Nothing will happen (because of a silenced error).

### Expected Behavior

Once the first application is accepted, we should automatically delete any other applications that have that same email.

### Additional Context

The [`acceptApplication`](https://github.com/colorstackorg/oyster/blob/311d09154629d73b7fec7cc3ac329280ce4cfb82/packages/core/src/modules/application/use-cases/accept-application.ts#L7) function is going to be the main focus of this issue.

**Comment by Boris713** [comment]
i can take this!

**Comment by wflore19** [comment]
i'll do this
